### PR TITLE
Stay in command mode after running a file, consistency in layout order

### PR DESCRIPTION
**Pull request by CelestialNebula**
I'm not very familiar with git/github so these changes got bundled together.

The only thing NEEDED is xah-fly-command-mode-activate and the README.md change, which adds unmentioned layouts, the others are just cause I wanted the order to be the same everywhere.

### CODE REVIEW

**Comment by xahlee** [comment]
sorry it's a bit confusing. The code to switch to command mode after run file is incorrect. also, it should be added as a hook by user. 
th change about rearange key layouts, seems there's lots changes, also about order of keys.

**Comment by xahlee** [comment]
also, is john doe the same as celestialNebula?

**Comment by CelestialNebula** [comment]
Yes, I had to do that change locally then push to github.

**Comment by CelestialNebula** [comment]
I messed up the Elisp, this is how it should look:
```
          (error "No recognized program file suffix for this file"))))
    (xah-fly-command-mode-activate)
    (run-hooks 'xah-run-current-file-after-hook)))
```

The reason I think this should be here is cause with
`
(add-hook 'shell-mode-hook 'xah-fly-insert-mode-activate)
`
being adding back when you run a shell file (for example) with `xah-run-current-file' it now makes you go into insert mode; whereas before you would stay in command mode.

**Pull request closed without merging**
